version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/examples/external-idp'
      - '/examples/simple'
      - '/examples/ssr'
    schedule:
      interval: 'weekly'
    groups:
      npm-dependencies:
        patterns:
          - '*'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      github-actions:
        patterns:
          - '*'
  - package-ecosystem: 'docker-compose'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      docker-images:
        patterns:
          - '*'
