services:
  dex:
    image: ghcr.io/dexidp/dex:v2.45.1
  nginx:
    image: nginx:1.31.3-alpine
  oauth2_proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.15.3
  socat:
    image: alpine/socat:1.8.1.3
