services:
  dex:
    image: ghcr.io/dexidp/dex:v2.45.1
  nginx:
    image: ghcr.io/blakearoberts/visage-nginx:next
  oauth2_proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.15.3
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.158.0-386
  socat:
    image: alpine/socat:1.8.1.3
