name: Checks

on:
  workflow_call:

permissions:
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          cache: npm
          node-version: 26

      - run: npm ci
      - run: npm run check
      - run: npm test
      - run: npm run build
      - run: npm pack --workspace @blakearoberts/visage

      - uses: actions/upload-artifact@v7
        with:
          archive: false
          path: '*.tgz'
          retention-days: 1

  e2e:
    name: E2E
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          cache: npm
          node-version: 26

      - name: Install mkcert and local CA
        run: |
          sudo apt-get update
          sudo apt-get install -y mkcert libnss3-tools
          mkdir -p "$HOME/.pki/nssdb"
          certutil -N --empty-password -d "sql:$HOME/.pki/nssdb"
          mkcert -install

      - name: Pull Docker images
        run: |
          docker compose -f packages/visage/docker-compose.images.yml pull
          docker pull traefik/whoami

      - run: npm ci
      - run: npm run test:e2e
        timeout-minutes: 3

      - if: always()
        uses: actions/upload-artifact@v7
        with:
          name: e2e-logs
          path: |
            test-results
            examples/simple/node_modules/.vite/visage/logs/**
            examples/ssr/.visage/logs/**
            examples/external-idp/node_modules/.vite/visage/logs/**
          include-hidden-files: true
          retention-days: 1
