name: Checks

on:
  workflow_call:

permissions:
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: 26

      - run: npm ci
      - run: npm run check
      - run: npm test
      - run: npm run build
      - name: npm pack
        run: |
          mkdir -p package
          npm pack --workspace @blakearoberts/visage --pack-destination package

      - uses: actions/upload-artifact@v7
        with:
          name: package
          path: package/*.tgz
          retention-days: 1

  e2e:
    name: E2E
    runs-on: ubuntu-latest
    needs: ci
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: 26

      - name: Install mkcert
        run: |
          sudo apt-get update
          sudo apt-get install -y mkcert

      - name: Pull Docker images
        run: |
          docker compose -f packages/visage/docker-compose.images.yml pull
          docker pull traefik/whoami

      - run: npm ci
      - run: npm run test:e2e
        timeout-minutes: 3
        env:
          PLAYWRIGHT_BROWSER_CHANNEL: chrome

      - if: always()
        uses: actions/upload-artifact@v7
        with:
          name: e2e-logs
          path: |
            test-results
            examples/simple/node_modules/.vite/visage/logs/**
            examples/ssr/.visage/logs/**
            examples/external-idp/node_modules/.vite/visage/logs/**
          include-hidden-files: true
          retention-days: 1
