name: Publish

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

concurrency:
  group: visage-publish-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: false

permissions:
  contents: read

env:
  PACKAGE_NAME: &package-name '@blakearoberts/visage'

jobs:
  publish-npm:
    name: Publish npm Package
    if: github.event.workflow_run.event == 'push' && github.event.workflow_run.conclusion == 'success'
    permissions:
      actions: read
      contents: read
      id-token: write
      pull-requests: read
    uses: ./.github/workflows/publish-npm.yml
    with:
      package-name: *package-name

  publish-release:
    name: Publish Release
    needs: publish-npm
    if: needs.publish-npm.outputs.stable-version != ''
    permissions:
      contents: read
    uses: ./.github/workflows/publish-gh.yml
    with:
      package-name: *package-name
      publish-version: ${{ needs.publish-npm.outputs.stable-version }}
    secrets: inherit
